### ISSUE TITLE
convert to sparse format

### ISSUE THREAD

**Issue by gongouveia** [arjun-majumdar/Neural_Network_Pruning#2]
Tensors after prunning are of the same dimensions as before but with 0s in it to denote pruned connection.
How could I cast tensors to sparse format? Any idea?

@arjun-majumdar

**Comment by arjun-majumdar** [comment]
Have you tried:

```
torch.Tensor.to_sparse()
```

Refer [here](https://pytorch.org/docs/stable/generated/torch.Tensor.to_sparse.html)

**Comment by arjun-majumdar** [comment]
Due to inactivity, I am closing this issue
